spring:
  datasource:
    username: pi
    password: ENC(+Tb6CL+hH5md5GjPcqoz2PRUrl2KopUp)
  application:
    name: subject
#  cloud:
#    client:
#      hostname: http://raspberrytronxi2.ddns.net
server:
  port: 8082
comun: application
environment: defecto