spring:
  datasource:
    username: pi
    password: servidortfg
  application:
    name: "subject"
  cloud:
    client:
      hostname: http://raspberrytronxi2.ddns.net
server:
  port: 8082
comun: application
environment: defecto