CREATE TABLE IF NOT EXISTS SUBJECT (
ID_SUBJECT int(10) NOT NULL AUTO_INCREMENT,
NAME VARCHAR(255),
YEAR VARCHAR(255),
CONSTRAINT PK_SUBJECT PRIMARY KEY
(ID_SUBJECT)
);

CREATE TABLE IF NOT EXISTS SUBJECT_USER(
ID_SUBJECT int(10) NOT NULL,
ID_USER int(10) NOT NULL,
CONSTRAINT PK_SUBJECT_USER PRIMARY KEY
(ID_SUBJECT, ID_USER)
);


CREATE TABLE IF NOT EXISTS USER_GROUP(
ID_GROUP int(10) NOT NULL,
ID_USER int(10) NOT NULL,
CONSTRAINT PK_USER_GROUP PRIMARY KEY
(ID_GROUP, ID_USER)
);

CREATE TABLE IF NOT EXISTS GROUPS(
ID_GROUP int(10) NOT NULL AUTO_INCREMENT,
ID_SUBJECT int(10) NOT NULL,
NAME_GROUP VARCHAR(255),
CONSTRAINT PK_GROUP PRIMARY KEY
(ID_GROUP)
);
